# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2 
    - run: flutter packages get
    - run: flutter pub get 
    - run: flutter build apk 
    - name: Upload to gdrive
      uses: https://drive.google.com/drive/folders/1dTrkQBUXjoj3iXO3Z5ax0gZwq0om71r8
      with:
          credentials: ${{ secrets.credentials }}
          filename: "build/app/outputs/flutter-apk/app-release.apk"
          folderId: ${{ secrets.folderId.outputs.value }}
          name: ${{steps.branch.outputs.banrch}}_apk_${{steps.date.output.date}}.apk
          overwrite: "true"     
